### ISSUE TITLE
error in loading inventory

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#257]
I used the latest tag but the inventory doesn't load. Did I forget anything?

```
[    c-scripting-core] Creating script environments for ox_inventory
[ script:ox_inventory] Error loading script modules/main.lua in resource ox_inventory: @ox_inventory/modules/main.lua:2: bad argument #1 to 'load' (function expected, got nil)
[ script:ox_inventory] stack traceback:
[ script:ox_inventory] 	[C]: in function 'load'
[ script:ox_inventory] 	@ox_inventory/modules/main.lua:2: in function 'data'
[ script:ox_inventory] 	[string "server.lua"]:3: in local 'func'
[ script:ox_inventory] 	@ox_inventory/modules/main.lua:32: in main chunk
[    c-scripting-core] Failed to load script modules/main.lua.
[ citizen-server-impl] Started resource ox_inventory
```

**Comment by thelindat** [comment]
This should have been fixed already, was due to an incorrect datafile being called.

**Comment by maxcamorra** [comment]
In the upcoming build? because in build 520247a the error is still there

**Comment by strongprincess** [comment]
[    c-scripting-core] Creating script environments for ox_inventory
[ script:ox_inventory] Error loading script modules/main.lua in resource ox_inventory: @modules/inventory/server.lua:584: attempt to call a nil value (global 'SetInterval')
[ script:ox_inventory] stack traceback:
[ script:ox_inventory] 	@modules/inventory/server.lua:584: in local 'func'
[ script:ox_inventory] 	@ox_inventory/modules/main.lua:13: in function 'module'
[ script:ox_inventory] 	@modules/shops/server.lua:2: in local 'func'
[ script:ox_inventory] 	@ox_inventory/modules/main.lua:13: in function 'module'
[ script:ox_inventory] 	@server.lua:4: in local 'func'
[ script:ox_inventory] 	@ox_inventory/modules/main.lua:33: in main chunk
[    c-scripting-core] Failed to load script modules/main.lua. 

this is my current issue and all i did was install

**Comment by dunak-debug** [comment]
https://overextended.github.io/ox_inventory/#framework
